# Generated by Django 3.2.5 on 2021-07-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
    ]
