# Generated by Django 3.2.5 on 2021-07-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0002_repuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='repuestos'),
        ),
    ]
