# Generated by Django 3.2.5 on 2021-07-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0003_repuesto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='marca',
            new_name='marcas',
        ),
    ]
