# Generated by Django 3.2.5 on 2021-07-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0004_rename_marca_repuesto_marcas'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
