# Generated by Django 3.2.5 on 2021-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0005_repuesto_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='comentario',
            field=models.TextField(default='--'),
        ),
    ]
