# Generated by Django 3.2.5 on 2021-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0006_repuesto_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
