# Generated by Django 3.2.5 on 2021-07-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0007_alter_repuesto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
