# Generated by Django 3.2.5 on 2021-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0008_repuesto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='duenno',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
