# Generated by Django 3.2.5 on 2021-07-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0009_repuesto_duenno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerMecanico.repuesto')),
            ],
        ),
    ]
